Compile the example
Unfortunately it does not, however I have a `extern crate rocket;` right there.
Any ideas?

```
failures:

---- src/response/responder.rs - response::responder::Responder (line 189) stdou
t ----
	error[E0433]: failed to resolve. Maybe a missing `extern crate rocket;`?
 --> src/response/responder.rs:6:5
  |
6 | use rocket::http::Status;
  |     ^^^^^^ Maybe a missing `extern crate rocket;`?

error[E0433]: failed to resolve. Maybe a missing `extern crate rocket;`?
 --> src/response/responder.rs:7:5
  |
7 | use rocket::request::Request;
  |     ^^^^^^ Maybe a missing `extern crate rocket;`?

error[E0433]: failed to resolve. Maybe a missing `extern crate rocket;`?
 --> src/response/responder.rs:8:5
  |
8 | use rocket::response::Response;
  |     ^^^^^^ Maybe a missing `extern crate rocket;`?

error[E0433]: failed to resolve. Maybe a missing `extern crate rocket;`?
 --> src/response/responder.rs:9:5
  |
9 | use rocket::response::Redirect;
  |     ^^^^^^ Maybe a missing `extern crate rocket;`?

error[E0433]: failed to resolve. Maybe a missing `extern crate rocket;`?
  --> src/response/responder.rs:10:5
```